### PR TITLE
fix fan_function to allow "auto" as percent value

### PR DESCRIPTION
**Pull request by braoult**

### CODE REVIEW

**Comment by braoult** [comment]
I wonder if I did not messed up the rebase... If it is not correct, let me know.

**Comment by JuampiCarosi** [comment]
You're still PR'ing with the "Merge branch" commit which I was trying to avoid lol, but nevermind, when I get home I'll cherry pick and push (keeping authorship ofc)

**Comment by JuampiCarosi** [comment]
Already merged into master.

**Comment by JuampiCarosi** [comment]
To avoid those commits add my repo as remote repo on your local machine and do a git merge of my branch instead of merging from GitHub

**Pull request closed without merging**
